name: CI Pipeline

#work on main branch and on pull requests to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# If a want that works on any branch:
# on:
#   push:

jobs:
  backend-lint: #first job in the pipeline: step on test for quality code
    name: Backend Lint #name of the job displayed in GitHub Actions UI
    runs-on: ubuntu-latest

    steps:
      # Clone the repository on the virtual machine
      - name: Checkout code
        uses: actions/checkout@v4 #clone the repo to the runner (ubuntu-latest) so that we can run the linting on the code

      # Install Node.js version 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: #use the latest version of Node.js 20. With in github CI / CD is keyword to specify argument of parameter
          node-version: "20"

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Install backend dependencies
      - name: Install dependencies
        run: cd backend && pnpm install

      # Run ESLint — blocks pipeline if errors
      # - name: Run lint
      #   run: cd backend && pnpm run lint

  backend-build:
    name: Backend Build & Push Docker Image
    runs-on: ubuntu-latest
    # needs: backend-lint  #wait for linting job to finish before starting the build job

    steps:
      # Clone the repository on the virtual machine
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with two tags
      # :latest → always the latest version
      # :sha    → unique identifier per commit for unique version
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # ← folder containing the Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

  # backend-deploy:
  #   name: Update K8s Manifest
  #   runs-on: ubuntu-latest
  #   needs: backend-build # ← wait for Docker image to be built and pushed

  #   steps:
  #     # Clone the INFRA repo (not the app repo)
  #     # This is where ArgoCD watches for changes
  #     - name: Checkout infra repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: guelate/StarupMatch-infra
  #         token: ${{ secrets.INFRA_REPO_TOKEN }}

  #     # Replace the old image tag with the new commit sha
  #     # ArgoCD will detect this change and deploy automatically
  #     - name: Update image tag
  #       run: |
  #         sed -i "s|image: ghcr.io/.*/backend:.*|image: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}|" k8s/deployment.yaml

  #     # Commit and push the change to the infra repo
  #     - name: Commit and push
  #       run: |
  #         git config user.email "ci@startupmatch.com"
  #         git config user.name "CI Bot"
  #         git add k8s/deployment.yaml
  #         git commit -m "ci: update backend image to ${{ github.sha }}"
  #         git push


# DANS LE README METTRE LES ETAPES DE SETTING: ( reprendre l'historique claude)
# Ton repo GitHub
# → Settings
# → Secrets and variables
# → Actions
# → New repository secret
# → Name: INFRA_REPO_TOKEN
# → Value: ton Personal Access Token

# ❌ Version manuelle verbose
# - run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
# - run: docker build -t ghcr.io/guelate/backend:latest ./backend
# - run: docker push ghcr.io/guelate/backend:latest

# # ✅ Version avec actions — fait exactement la même chose
# - uses: docker/login-action@v3
# - uses: docker/build-push-action@v5


#Faire une partie doc dans le readme 
# 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
#todo: explain how to build and push image on Github container registry. 
# To build image: docker build -t ghcr.io/<username>/<repo>:<tag> .
# To push image: docker push ghcr.io/<username>/<repo>:<tag>

# Run image:
# docker run ghcr.io/guelate/backend:latest
#         ↓
# Docker cherche l'image en local
#         ↓
# ❌ Image non trouvée localement (si elle a été supprimée de docker)
#         ↓
# Docker pull automatiquement depuis GHCR
#         ↓
# ✅ Image téléchargée et container lancé